Repository OpenZeppelin/openzeppelin-monitor, pull requests merged in 2025-04, with the labels that each got.

#160 chore: Change release readme to release readme
  .github/RELEASE.md
Labels: cla: allowlist

#161 chore: Add npm ci
  netlify.toml
Labels: cla: allowlist

#162 fix: Netlify integration & Release workflow doc
  .github/RELEASE.md
  netlify.toml
Labels: cla: allowlist

#163 chore: temporary remove link to technical rust docs
  Cargo.lock
  docs/modules/ROOT/nav.adoc
Labels: cla: allowlist

#119 chore: Add link to documentation when config fails
  CONTRIBUTING.md
  Cargo.lock
  README.md
  docs/modules/ROOT/pages/index.adoc
  docs/modules/ROOT/pages/quickstart.adoc
  docs/modules/ROOT/pages/rpc.adoc
  docs/modules/ROOT/pages/scripts.adoc
  src/main.rs
  src/utils/constants.rs
  src/utils/mod.rs
  tests/integration/mocks/logging.rs
Labels: cla: allowlist

#167 fix: Docs pipeline
  .github/release-please/.config.json
  .github/workflows/release-bins.yml
  .github/workflows/release-docker.yml
  .github/workflows/release-docs.yml
  .github/workflows/release-please.yml
  .github/workflows/scorecard.yml
  .typos.toml
  Cargo.lock
  README.md
  docs/antora.yml
  docs/package-lock.json
  docs/package.json
Labels: cla: allowlist

#174 fix: remove the create-github-app-token action from the scorecard workflow
  .github/workflows/scorecard.yml
  Cargo.lock
Labels: cla: allowlist

#133 feat: Test execute the monitor against specific block
  Cargo.lock
  Cargo.toml
  docs/modules/ROOT/pages/index.adoc
  docs/modules/ROOT/pages/quickstart.adoc
  src/main.rs
  src/repositories/monitor.rs
  src/services/blockchain/clients/stellar/client.rs
  src/utils/logging/error.rs
  src/utils/logging/mod.rs
  src/utils/metrics/mod.rs
  src/utils/mod.rs
  src/utils/monitor/error.rs
  src/utils/monitor/execution.rs
  src/utils/monitor/mod.rs
  src/utils/script/executor.rs
  tests/integration.rs
  tests/integration/blockchain/clients/stellar/client.rs
  tests/integration/filters/common.rs
  tests/integration/mocks/logging.rs
  tests/integration/mocks/repositories.rs
  tests/integration/monitor/execution.rs
Labels: do-not-merge, cla: allowlist

#176 fix: CLA labels and assistant
  .github/workflows/cla.yml
  .pre-commit-config.yaml
  .yamlfix.toml
  Cargo.lock
Labels: cla: allowlist, cla: unsigned

#132 chore: Adding Optimism network samples
  .gitignore
  Cargo.lock
  README.md
  config/filters/.keep
  config/monitors/.keep
  config/networks/.keep
  config/triggers/.keep
  config/triggers/scripts/.keep
  docs/modules/ROOT/pages/index.adoc
  docs/modules/ROOT/pages/quickstart.adoc
  docs/modules/ROOT/pages/structure.adoc
  examples/config/filters/evm_filter_block_number.js
  examples/config/filters/evm_filter_block_number.py
  examples/config/filters/evm_filter_block_number.sh
  examples/config/filters/stellar_filter_block_number.js
  examples/config/filters/stellar_filter_block_number.py
  examples/config/filters/stellar_filter_block_number.sh
  examples/config/monitors/evm_transfer_usdc.json
  examples/config/monitors/stellar_swap_dex.json
  examples/config/networks/ethereum_mainnet.json
  examples/config/networks/optimism_mainnet.json
  examples/config/networks/optimism_sepolia.json
  examples/config/networks/stellar_mainnet.json
  examples/config/networks/stellar_testnet.json
  examples/config/networks/unichain_sepolia.json
  examples/config/triggers/discord_notifications.json
  examples/config/triggers/email_notifications.json
  examples/config/triggers/script_notifications.json
  examples/config/triggers/scripts/custom_notification.js
  examples/config/triggers/scripts/custom_notification.py
  examples/config/triggers/scripts/custom_notification.sh
  examples/config/triggers/slack_notifications.json
  examples/config/triggers/telegram_notifications.json
  examples/config/triggers/webhook_notifications.json
  scripts/validate_network_config.sh
Labels: cla: allowlist

#181 fix: Running duplicate tests
  .github/workflows/ci.yaml
  .gitignore
Labels: cla: allowlist

#184 chore: update docs branch and actions/create-github-app-toke version
  .github/workflows/rc.yml
  .github/workflows/release-bins.yml
  .github/workflows/release-docker.yml
  .github/workflows/release-docs.yml
  .github/workflows/release-please.yml
  .github/workflows/release-sbom.yml
  Cargo.lock
Labels: cla: allowlist

#185 chore: Refactor notifiers to re-use webhook notifier
  Cargo.lock
  src/services/notification/discord.rs
  src/services/notification/mod.rs
  src/services/notification/slack.rs
  src/services/notification/telegram.rs
  src/services/notification/webhook.rs
  tests/integration/notifications/discord.rs
  tests/integration/notifications/webhook.rs
  tests/properties/notifications/webhook.rs
Labels: cla: allowlist

#193 chore: Add `--check` flag and improves cli opts readability
  Cargo.lock
  Cargo.toml
  docs/modules/ROOT/pages/index.adoc
  docs/modules/ROOT/pages/quickstart.adoc
  src/main.rs
  src/utils/mod.rs
  src/utils/parsing.rs
Labels: cla: allowlist

#198 fix: Event and function signatures from matched_on
  Cargo.lock
  src/services/filter/filter_match.rs
  tests/integration/filters/evm/filter.rs
  tests/integration/filters/stellar/filter.rs
  tests/integration/fixtures/evm/blocks.json
  tests/integration/fixtures/evm/monitors/monitor.json
  tests/integration/fixtures/evm/transaction_receipts.json
  tests/integration/fixtures/stellar/monitors/monitor.json
  tests/integration/fixtures/stellar/transactions.json
Labels: T-bug, cla: allowlist

#196 chore: Add test helpers with builder pattern for core models
  README.md
  docs/modules/ROOT/pages/structure.adoc
  src/bootstrap/mod.rs
  src/models/config/monitor_config.rs
  src/models/config/network_config.rs
  src/models/config/trigger_config.rs
  src/repositories/monitor.rs
  src/services/blockwatcher/tracker.rs
  src/services/filter/filters/evm/filter.rs
  src/services/notification/mod.rs
  src/services/notification/script.rs
  src/services/trigger/script/executor.rs
  src/utils/metrics/mod.rs
  src/utils/metrics/server.rs
  src/utils/mod.rs
  src/utils/tests/builders/evm/monitor.rs
  src/utils/tests/builders/network.rs
  src/utils/tests/builders/stellar/monitor.rs
  src/utils/tests/builders/trigger.rs
  src/utils/tests/mod.rs
  tests/integration/blockchain/pool.rs
  tests/integration/bootstrap/main.rs
  tests/integration/mocks/models.rs
  tests/integration/monitor/execution.rs
  tests/integration/notifications/discord.rs
  tests/integration/notifications/script.rs
  tests/integration/notifications/slack.rs
  tests/integration/notifications/webhook.rs
  tests/properties/filters/evm/filter.rs
  tests/properties/filters/stellar/filter.rs
  tests/properties/strategies.rs
Labels: cla: allowlist
